/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2019 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Clock.h"
#include "m_miso_pin_aliases.h"
#include "m_miso_pin.h"
#include "m_mosi_pin_aliases.h"
#include "m_mosi_pin.h"
#include "m_sclk_pin_aliases.h"
#include "m_sclk_pin.h"
#include "SPIM.h"
#include "SPIM_PVT.h"
#include "m_ss_pin_aliases.h"
#include "m_ss_pin.h"
#include "IRQ.h"
#include "pin_1_aliases.h"
#include "pin_1.h"
#include "LED_1_aliases.h"
#include "LED_1.h"
#include "LED_2_aliases.h"
#include "LED_2.h"
#include "LED_3_aliases.h"
#include "LED_3.h"
#include "LED_4_aliases.h"
#include "LED_4.h"
#include "Timer_1.h"
#include "timer_clock.h"
#include "rst_in_aliases.h"
#include "rst_in.h"
#include "USBP.h"
#include "USBP_audio.h"
#include "USBP_cdc.h"
#include "USBP_hid.h"
#include "USBP_midi.h"
#include "USBP_pvt.h"
#include "USBP_cydmac.h"
#include "USBP_msc.h"
#include "GPIOJ11_aliases.h"
#include "GPIOJ11.h"
#include "GPIOJ12_aliases.h"
#include "GPIOJ12.h"
#include "GPIOJ13_aliases.h"
#include "GPIOJ13.h"
#include "GPIOJ14_aliases.h"
#include "GPIOJ14.h"
#include "USBP_Dm_aliases.h"
#include "USBP_Dm.h"
#include "USBP_Dp_aliases.h"
#include "USBP_Dp.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

